---
apiVersion: v1
kind: Service
metadata:
  name: stock-alt-geolocation
spec:
  type: ClusterIP
  selector:
    app: stock-alt-geolocation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
