---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-alt-geolocation

images:
  - name: stock-alt-geolocation
    newName: stock-alt-geolocation
    newTag: latest
